apiVersion: apps/v1
kind: Deployment
metadata:
  name: arca-agency-banking-portal
  
spec:
  selector:
    matchLabels:
      app: merchant
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: merchant
    spec:
      containers:
      - name: merchant-api
        image: ${REPOSITORY_TAG}
        resources:
          requests:
             memory: 512Mi
             cpu: 0.5
#         env:
#         - name: SPRING_PROFILES_ACTIVE
#           value: production-microservice
        imagePullPolicy: Always
#         readinessProbe:
#           httpGet:
#             path: /healthz
#             port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: arca-agency-banking-portal-svc
  namespace: arca-agency-banking

spec:
 
  selector:
    app: agency-banking-portal

  ports:
    - name: http
      port: 4200
 

  type: LoadBalancer
