apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-api
  
spec:
  selector:
    matchLabels:
      app: merchant
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: merchant
    spec:
      containers:
      - name: merchant
        image: ${REPOSITORY_TAG}
        resources:
          requests:
             memory: 512Mi
             cpu: 0.5

        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: merchant-svc
  
spec:
 
  selector:
    app: merchant

  ports:
    - name: http
      port: 80
      nodePort: 30000
 

  type: NodePort
